version: '3.5'

services:
  sbt_env:
    build:
      context: .
      args:
        CUR_DIR: ${CUR_DIR}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USER: ${USER}
    user: ${USER_ID}:${GROUP_ID}
    container_name: calc_env
    ports:
      - "8080:8080"
    volumes:
      - ${CUR_DIR}:${HOME}/app
      - /home/${USER}/.ssh:/home/user/.ssh:ro
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    working_dir: ${HOME}/app
    tty: true
