version: '3.5'

services:
  sbt_env:
    build: .
    user:
      1000:1000
    volumes:
      - ./:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    working_dir: /app
    tty: true
